---
version: 1.2.3
name: Stardeus
description: Sci-fi space colony management simulator
url: https://stardeusgame.com
repository: https://github.com/kodolinija/stardeus-website
timezone: Europe/Vilnius
twitter:
  username: StardeusGame
logo: "/img/stardeus-logo.png"
google_analytics_id: UA-203669382-2
google_site_verification: google-site-verification=j6oAVRZpFG8wLabJ_KaDDyowkVXhgZ9WtlLLNL2NI-w
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
  posts:
    permalink: "/news/:year/:month/:day/:title/"
    output: true
  tutorials:
    permalink: "/:collection/:path/"
    output: true
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: news_item
- scope:
    path: ''
  values:
    image: "/img/stardeus-cover-og.jpg"
future: true
plugins:
- jekyll-avatar
#- jekyll-feed
- jekyll-mentions
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji
feed:
  categories:
  - release
kramdown:
  syntax_highlighter_opts:
    default_lang: plaintext
sass:
  style: compressed
strict_front_matter: true
exclude:
- icomoon-selection.json
- readme.md
